import SubmitFailedCharacterExerciseDetailsRequestModel from "@/models/requests/SubmitFailedCharacterExerciseDetailsRequest.Model";

export default interface SubmitFailedCharacterExerciseDetailsResponseModel {
  request: SubmitFailedCharacterExerciseDetailsRequestModel;
}
