**/.env
**/.git
**/.gitattributes
**/.gitignore
**/.vs
**/.vscode
**/*.*proj.user
**/*.dbmdl
**/*.jfm

**/bin
**/obj
**/build
**/node_modules
**/charts
**/secrets.dev.yaml
**/values.dev.yaml

CHANGELOG.md
CONTRIBUTING.md
LICENSE.md
README.md
