// <auto-generated />
using JapaneseLanguageTools.Data.Sqlite.Contexts;

using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace JapaneseLanguageTools.Data.Sqlite.Migrations
{
    [DbContext(typeof(SqliteMainDbContext))]
    [Migration("20250722180727_InitialMigration")]
    partial class InitialMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.7");
#pragma warning restore 612, 618
        }
    }
}
