// <auto-generated />
using JapaneseLanguageTools.Data.Sqlite.Contexts;

using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace JapaneseLanguageTools.Data.Sqlite.Migrations
{
    [DbContext(typeof(SqliteMainDbContext))]
    [Migration("20250727172637_TagMigration")]
    partial class TagMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.7");

            modelBuilder.Entity("JapaneseLanguageTools.Data.Entities.Tag", b =>
            {
                b.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("INTEGER");

                b.Property<string>("Caption")
                    .IsRequired()
                    .HasMaxLength(256)
                    .HasColumnType("TEXT");

                b.Property<string>("CreatedOn")
                    .IsRequired()
                    .ValueGeneratedOnAdd()
                    .HasColumnType("TEXT")
                    .HasDefaultValueSql("STRFTIME('%F %T+00:00', 'now')");

                b.Property<string>("PlaceholderMarker")
                    .HasMaxLength(2048)
                    .HasColumnType("TEXT");

                b.Property<string>("UpdatedOn")
                    .IsRequired()
                    .ValueGeneratedOnAdd()
                    .HasColumnType("TEXT")
                    .HasDefaultValueSql("STRFTIME('%F %T+00:00', 'now')");

                b.HasKey("Id");

                b.HasIndex("Caption")
                    .IsUnique()
                    .HasDatabaseName("UIX_Tag_Caption");

                b.ToTable("Tag", null, t =>
                {
                    t.HasCheckConstraint("CK_Tag_Caption_MaxLength", "LENGTH(TRIM(\"Caption\")) <= 256");

                    t.HasCheckConstraint("CK_Tag_Caption_NotEmpty", "LENGTH(TRIM(\"Caption\")) > 0");

                    t.HasCheckConstraint("CK_Tag_PlaceholderMarker_NullOrMaxLength", "\"PlaceholderMarker\" IS NULL OR LENGTH(TRIM(\"PlaceholderMarker\")) <= 2048");

                    t.HasCheckConstraint("CK_Tag_PlaceholderMarker_NullOrNotEmpty", "\"PlaceholderMarker\" IS NULL OR LENGTH(TRIM(\"PlaceholderMarker\")) > 0");
                });
            });
#pragma warning restore 612, 618
        }
    }
}
