// <auto-generated />
using System;

using JapaneseLanguageTools.Data.SqlServer.Contexts;

using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace JapaneseLanguageTools.Data.SqlServer.Migrations
{
    [DbContext(typeof(SqlServerMainDbContext))]
    [Migration("20250727180140_CharacterExerciseMigration")]
    partial class CharacterExerciseMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            modelBuilder.UseIdentityColumns();

            modelBuilder.Entity("JapaneseLanguageTools.Data.Entities.Character", b =>
            {
                b.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("int");

                b.Property<int>("Id")
                    .UseIdentityColumn();

                b.Property<int?>("CharacterGroupId")
                    .HasColumnType("int");

                b.Property<DateTimeOffset>("CreatedOn")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("datetimeoffset");

                b.Property<string>("Kunyomi")
                    .HasMaxLength(256)
                    .HasColumnType("nvarchar(256)");

                b.Property<string>("Meaning")
                    .HasMaxLength(512)
                    .HasColumnType("nvarchar(512)");

                b.Property<string>("Onyomi")
                    .HasMaxLength(256)
                    .HasColumnType("nvarchar(256)");

                b.Property<string>("Pronunciation")
                    .HasMaxLength(32)
                    .HasColumnType("nvarchar(32)");

                b.Property<string>("Syllable")
                    .HasMaxLength(32)
                    .HasColumnType("nvarchar(32)");

                b.Property<string>("Symbol")
                    .IsRequired()
                    .HasMaxLength(16)
                    .HasColumnType("nvarchar(16)");

                b.Property<int>("Type")
                    .HasColumnType("int");

                b.Property<DateTimeOffset>("UpdatedOn")
                    .ValueGeneratedOnAddOrUpdate()
                    .HasColumnType("datetimeoffset");

                b.HasKey("Id");

                b.HasIndex("CharacterGroupId")
                    .HasDatabaseName("IX_Character_CharacterGroupId");

                b.ToTable("Character", "dbo", t =>
                {
                    t.HasCheckConstraint("CK_Character_Kunyomi_NullOrNotEmpty", "[Kunyomi] IS NULL OR LEN(TRIM([Kunyomi])) > 0");

                    t.HasCheckConstraint("CK_Character_Meaning_NullOrNotEmpty", "[Meaning] IS NULL OR LEN(TRIM([Meaning])) > 0");

                    t.HasCheckConstraint("CK_Character_Onyomi_NullOrNotEmpty", "[Onyomi] IS NULL OR LEN(TRIM([Onyomi])) > 0");

                    t.HasCheckConstraint("CK_Character_Pronunciation_NullOrNotEmpty", "[Pronunciation] IS NULL OR LEN(TRIM([Pronunciation])) > 0");

                    t.HasCheckConstraint("CK_Character_Syllable_NullOrNotEmpty", "[Syllable] IS NULL OR LEN(TRIM([Syllable])) > 0");

                    t.HasCheckConstraint("CK_Character_Symbol_NotEmpty", "LEN(TRIM([Symbol])) > 0");
                });
            });

            modelBuilder.Entity("JapaneseLanguageTools.Data.Entities.CharacterExercise", b =>
            {
                b.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("int");

                b.Property<int>("Id")
                    .UseIdentityColumn();

                b.Property<int>("CharacterId")
                    .HasColumnType("int");

                b.Property<DateTimeOffset>("GeneratedOn")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("datetimeoffset");

                b.Property<string>("InstanceData")
                    .HasMaxLength(2048)
                    .HasColumnType("nvarchar(2048)");

                b.HasKey("Id");

                b.HasIndex("CharacterId")
                    .HasDatabaseName("IX_CharacterExercise_CharacterId");

                b.ToTable("CharacterExercise", "dbo", t =>
                {
                    t.HasCheckConstraint("CK_CharacterExercise_InstanceData_NullOrNotEmpty", "[InstanceData] IS NULL OR LEN(TRIM([InstanceData])) > 0");
                });
            });

            modelBuilder.Entity("JapaneseLanguageTools.Data.Entities.CharacterExerciseRerun", b =>
            {
                b.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("int");

                b.Property<int>("Id")
                    .UseIdentityColumn();

                b.Property<int>("CharacterExerciseId")
                    .HasColumnType("int");

                b.Property<int>("ContinuousChallengeCount")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("int")
                    .HasDefaultValue(0);

                b.Property<DateTimeOffset>("InitiallyScheduledOn")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("datetimeoffset");

                b.Property<DateTimeOffset>("RepeatedlyScheduledOn")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("datetimeoffset");

                b.Property<int>("RequiredChallengeCount")
                    .HasColumnType("int");

                b.Property<int>("TotalChallengeCount")
                    .HasColumnType("int");

                b.HasKey("Id");

                b.HasIndex("CharacterExerciseId")
                    .HasDatabaseName("IX_CharacterExerciseRerun_CharacterExerciseId");

                b.ToTable("CharacterExerciseRerun", "dbo", t =>
                {
                    t.HasCheckConstraint("CK_CharacterExerciseRerun_ContinuousChallengeCount_NotNegative", "[ContinuousChallengeCount] >= 0");

                    t.HasCheckConstraint("CK_CharacterExerciseRerun_RequiredChallengeCount_NotNegative", "[RequiredChallengeCount] >= 0");

                    t.HasCheckConstraint("CK_CharacterExerciseRerun_TotalChallengeCount_NotNegative", "[TotalChallengeCount] >= 0");
                });
            });

            modelBuilder.Entity("JapaneseLanguageTools.Data.Entities.CharacterGroup", b =>
            {
                b.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("int");

                b.Property<int>("Id")
                    .UseIdentityColumn();

                b.Property<bool>("AlwaysUse")
                    .HasColumnType("bit");

                b.Property<string>("Caption")
                    .IsRequired()
                    .HasMaxLength(256)
                    .HasColumnType("nvarchar(256)");

                b.Property<string>("Comment")
                    .HasMaxLength(2048)
                    .HasColumnType("nvarchar(2048)");

                b.Property<DateTimeOffset>("CreatedOn")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("datetimeoffset");

                b.Property<bool>("Enabled")
                    .HasColumnType("bit");

                b.Property<bool>("Hidden")
                    .HasColumnType("bit");

                b.Property<DateTimeOffset>("UpdatedOn")
                    .ValueGeneratedOnAddOrUpdate()
                    .HasColumnType("datetimeoffset");

                b.HasKey("Id");

                b.HasAlternateKey("Caption");

                b.HasIndex("Caption")
                    .IsUnique()
                    .HasDatabaseName("UIX_CharacterGroup_Caption");

                b.ToTable("CharacterGroup", "dbo", t =>
                {
                    t.HasCheckConstraint("CK_CharacterGroup_Caption_NotEmpty", "LEN(TRIM([Caption])) > 0");

                    t.HasCheckConstraint("CK_CharacterGroup_Comment_NullOrNotEmpty", "[Comment] IS NULL OR LEN(TRIM([Comment])) > 0");
                });
            });

            modelBuilder.Entity("JapaneseLanguageTools.Data.Entities.CharacterTag", b =>
            {
                b.Property<int>("CharacterId")
                    .HasColumnType("int");

                b.Property<int>("TagId")
                    .HasColumnType("int");

                b.HasKey("CharacterId", "TagId");

                b.HasIndex("CharacterId")
                    .HasDatabaseName("IX_CharacterTag_CharacterId");

                b.HasIndex("TagId")
                    .HasDatabaseName("IX_CharacterTag_TagId");

                b.ToTable("CharacterTag", "dbo");
            });

            modelBuilder.Entity("JapaneseLanguageTools.Data.Entities.Tag", b =>
            {
                b.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("int");

                b.Property<int>("Id")
                    .UseIdentityColumn();

                b.Property<string>("Caption")
                    .IsRequired()
                    .HasMaxLength(256)
                    .HasColumnType("nvarchar(256)");

                b.Property<DateTimeOffset>("CreatedOn")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("datetimeoffset");

                b.Property<string>("PlaceholderMarker")
                    .HasMaxLength(2048)
                    .HasColumnType("nvarchar(2048)");

                b.Property<DateTimeOffset>("UpdatedOn")
                    .ValueGeneratedOnAddOrUpdate()
                    .HasColumnType("datetimeoffset");

                b.HasKey("Id");

                b.HasAlternateKey("Caption");

                b.HasIndex("Caption")
                    .IsUnique()
                    .HasDatabaseName("UIX_Tag_Caption");

                b.ToTable("Tag", "dbo", t =>
                {
                    t.HasCheckConstraint("CK_Tag_Caption_NotEmpty", "LEN(TRIM([Caption])) > 0");

                    t.HasCheckConstraint("CK_Tag_PlaceholderMarker_NullOrNotEmpty", "[PlaceholderMarker] IS NULL OR LEN(TRIM([PlaceholderMarker])) > 0");
                });
            });

            modelBuilder.Entity("JapaneseLanguageTools.Data.Entities.Character", b =>
            {
                b.HasOne("JapaneseLanguageTools.Data.Entities.CharacterGroup", "CharacterGroup")
                    .WithMany("Characters")
                    .HasForeignKey("CharacterGroupId")
                    .OnDelete(DeleteBehavior.Restrict);

                b.Navigation("CharacterGroup");
            });

            modelBuilder.Entity("JapaneseLanguageTools.Data.Entities.CharacterExercise", b =>
            {
                b.HasOne("JapaneseLanguageTools.Data.Entities.Character", "Character")
                    .WithMany()
                    .HasForeignKey("CharacterId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();

                b.Navigation("Character");
            });

            modelBuilder.Entity("JapaneseLanguageTools.Data.Entities.CharacterExerciseRerun", b =>
            {
                b.HasOne("JapaneseLanguageTools.Data.Entities.CharacterExercise", "CharacterExercise")
                    .WithMany("CharacterExerciseReruns")
                    .HasForeignKey("CharacterExerciseId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();

                b.Navigation("CharacterExercise");
            });

            modelBuilder.Entity("JapaneseLanguageTools.Data.Entities.CharacterTag", b =>
            {
                b.HasOne("JapaneseLanguageTools.Data.Entities.Character", "Character")
                    .WithMany("CharacterTags")
                    .HasForeignKey("CharacterId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();

                b.HasOne("JapaneseLanguageTools.Data.Entities.Tag", "Tag")
                    .WithMany()
                    .HasForeignKey("TagId")
                    .OnDelete(DeleteBehavior.Restrict)
                    .IsRequired();

                b.Navigation("Character");

                b.Navigation("Tag");
            });

            modelBuilder.Entity("JapaneseLanguageTools.Data.Entities.Character", b =>
            {
                b.Navigation("CharacterTags");
            });

            modelBuilder.Entity("JapaneseLanguageTools.Data.Entities.CharacterExercise", b =>
            {
                b.Navigation("CharacterExerciseReruns");
            });

            modelBuilder.Entity("JapaneseLanguageTools.Data.Entities.CharacterGroup", b =>
            {
                b.Navigation("Characters");
            });
#pragma warning restore 612, 618
        }
    }
}
