// <auto-generated />
using System;

using JapaneseLanguageTools.Data.SqlServer.Contexts;

using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace JapaneseLanguageTools.Data.SqlServer.Migrations
{
    [DbContext(typeof(SqlServerMainDbContext))]
    [Migration("20250727172707_TagMigration")]
    partial class TagMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            modelBuilder.UseIdentityColumns();

            modelBuilder.Entity("JapaneseLanguageTools.Data.Entities.Tag", b =>
            {
                b.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("int");

                b.Property<int>("Id")
                    .UseIdentityColumn();

                b.Property<string>("Caption")
                    .IsRequired()
                    .HasMaxLength(256)
                    .HasColumnType("nvarchar(256)");

                b.Property<DateTimeOffset>("CreatedOn")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("datetimeoffset");

                b.Property<string>("PlaceholderMarker")
                    .HasMaxLength(2048)
                    .HasColumnType("nvarchar(2048)");

                b.Property<DateTimeOffset>("UpdatedOn")
                    .ValueGeneratedOnAddOrUpdate()
                    .HasColumnType("datetimeoffset");

                b.HasKey("Id");

                b.HasAlternateKey("Caption");

                b.HasIndex("Caption")
                    .IsUnique()
                    .HasDatabaseName("UIX_Tag_Caption");

                b.ToTable("Tag", "dbo", t =>
                {
                    t.HasCheckConstraint("CK_Tag_Caption_NotEmpty", "LEN(TRIM([Caption])) > 0");

                    t.HasCheckConstraint("CK_Tag_PlaceholderMarker_NullOrNotEmpty", "[PlaceholderMarker] IS NULL OR LEN(TRIM([PlaceholderMarker])) > 0");
                });
            });
#pragma warning restore 612, 618
        }
    }
}
